name: admin_signup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  image_picker: ^1.0.4
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  lucide_icons: ^0.257.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  fl_chart: ^0.70.2
  web_socket_channel: ^3.0.2
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.4
  sensors_plus: ^6.1.1
  path_provider: ^2.1.5
  csv: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/HowAmIDriving.png
    - assets/images/adddriver.png
    - assets/images/geofence.png
    - assets/images/track.png
    - assets/images/vehiclefront.png
    - assets/images/boundSpeedlimit.png
    - assets/images/Trackall.png